version: '3.9'
services:
  my-site-nginx:
    build:
      context: "./docker/nginx"
    depends_on:
      - my-site-php-fpm
    volumes:
      - ./docker/nginx/ssl/:/etc/nginx/ssl
      - './shopy-web/ShopyApp:/var/www/html'
      - ./docker/logs/nginx/:/var/log/nginx
      - ./docker/nginx/sites/:/etc/nginx/sites-available
    ports:
      - "4044:443"
      - "8083:80"
    networks:
      - my-site

  my-site-php-fpm:
    build:
      context: "./docker/php-fpm"
    volumes:
      - './shopy-web/ShopyApp:/var/www/html'
    networks:
      - my-site
    expose:
      - "9002:9000"

  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '${FORWARD_DB_PORT:-33006}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: 'shopy'
      MYSQL_USER: 'shopy'
      MYSQL_PASSWORD: 'root'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      # DB_CONNECTION : "mysql"
      # DB_HOST : ""
      # DB_PORT: ""
      # DB_DATABASE : ""
      # DB_USERNAME : ""
      # DB_PASSWORD : ""
    volumes:
      - 'my-site-mysql:/var/lib/mysql'
    networks:
      - my-site
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p root" ]
      retries: 3
      timeout: 5s

  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - '${FORWARD_MAILHOG_PORT:-1025}:1025'
      - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
    networks:
      - my-site

networks:
  my-site:
    driver: bridge
volumes:
  my-site-mysql:
    driver: local
